# Generated by Django 4.2.7 on 2023-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finesweetapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('previewText', models.CharField(blank=True, max_length=250)),
                ('previewIcon', models.URLField(blank=True)),
                ('hoverPreviewIcon', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='hoverPreviewIcon',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='mainImage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='mainText',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='services',
            name='mainTitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='previewIcon',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='previewText',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='services',
            name='quotation',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='services',
            name='subText',
            field=models.CharField(blank=True, max_length=750),
        ),
        migrations.AlterField(
            model_name='services',
            name='subTitle',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
