# Generated by Django 4.2.7 on 2023-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finesweetapi', '0005_brands_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesPreview',
        ),
        migrations.AlterField(
            model_name='services',
            name='mainTitle',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
